spring:
  application:
    name: Qiyu-Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?useSSL=false&autoReconnect=true
    username: root
    password: 19951193HB
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 127.0.0.1:2181
      rootDir: file:///D:/programming/HBase
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9528

logging:
  file: qiyu-passbook.log
  level: debug
